[[plugins]]
package = "netlify-plugin-cache-nextjs"
    # These options will cache the build directory at `${NETLIFY_BASE}/out/.next-build`
	[plugins.inputs]
	# The path to the build directory
	build_dir_path = "out"
	# Custom build directory if you aren't using `.next` (https://nextjs.org/docs/api-reference/next.config.js/setting-a-custom-build-directory)
	custom_build_dir_name = ".next-build"